version: '3'

services:

    #pg82:
    #  container_name: pg82
    #  ports:
    #    - "1082:5432"
    #  image: datagrip/postgres:8.2
    #  env_file: my.env

    pg84:
      container_name: pg84
      ports:
        - "1084:5432"
      image: postgres:8.4
      env_file: my.env

    pg90:
      container_name: pg90
      ports:
        - "1090:5432"
      image: postgres:9.0
      env_file: my.env

    pg91:
      container_name: pg91
      ports:
        - "1091:5432"
      image: postgres:9.1
      env_file: my.env

    pg92:
      container_name: pg92
      ports:
        - "1092:5432"
      image: postgres:9.2-alpine
      env_file: my.env

    pg93:
      container_name: pg93
      ports:
        - "1093:5432"
      image: postgres:9.3-alpine
      env_file: my.env

    pg94:
      container_name: pg94
      ports:
        - "1094:5432"
      image: postgres:9.4-alpine
      env_file: my.env

    pg95:
      container_name: pg95
      ports:
        - "1095:5432"
      image: postgres:9.5-alpine
      env_file: my.env

    pg96:
      container_name: pg96
      ports:
        - "1096:5432"
      image: postgres:9.6-alpine
      env_file: my.env

    mysql51:
      container_name: mysql51
      ports:
        - "33051:3306"
      image: datagrip/mysql:5.1
      env_file: my.env

    mysql55:
      container_name: mysql55
      privileged: true
      ports:
        - "33055:3306"
      image: mysql:5.5
      env_file: my.env
      command: [mysqld, --character-set-server=utf8]

    mysql56:
      container_name: mysql56
      ports:
        - "33056:3306"
      image: mysql:5.6
      env_file: my.env
      command: [mysqld, --character-set-server=utf8]

    mysql57:
      container_name: mysql57
      ports:
        - "33057:3306"
      image: mysql:5.7
      env_file: my.env
      command: [mysqld, --character-set-server=utf8]

    mysql80:
      container_name: mysql80
      image: mysql:8.0
      ports:
        - "33080:3306"
      env_file: my.env
      command: [mysqld, --character-set-server=utf8]

    maria10:
      container_name: maria10
      ports:
        - "33040:3306"
      image: mariadb:10.0
      env_file: my.env

    # oracle VM options
    # -Duser.country=en -Duser.language=en
    # todo: use debian:wheezy
    oracle11:
      container_name: oracle11
      ports:
        - "1521:1521"
      image: datagrip/oracle:11.2
      env_file: my.env

    db2:
      container_name: db2
      privileged: true
      image: datagrip/db2
      ports:
        - "50000:50000"
      env_file: my.env

    hsql200:
      container_name: hsql200
      image: datagrip/hsqldb:2.0.0
      ports:
        - "9001:9001"
      env_file: my.env

    hsql233:
      container_name: hsql233
      image: datagrip/hsqldb:2.3.3
      ports:
        - "9002:9001"
      env_file: my.env

    derby1011:
      container_name: derby1011
      image: datagrip/derby-server:10.11
      ports:
        - "1527:1527"
      env_file: my.env

    derby1012:
      container_name: derby1012
      image: datagrip/derby-server:10.12
      ports:
        - "1528:1527"
      env_file: my.env

    h2:
      container_name: h2
      image: datagrip/h2:1.3
      ports:
        - "9092:9092"
      env_file: my.env

    # needs about 30 seconds for proper start and initialization
    sybase:
      container_name: sybase
      image: datagrip/sybase:15.7
      ports:
        - "5000:5000"
      env_file: my.env
      hostname: dksybase

    mssql:
      container_name: mssql
      privileged: true
      image: datagrip/mssql-server-linux
      ports:
        - "1433:1433"
      env_file: my.env

