insert into Tannenbaum(My_Column,                                    X)
values                ('O',                                          0),
                      ('O T',                                        0),
                      ('O Ta',                                       0),
                      ('O Tan',                                      0),
                      ('O Tann',                                     0),
                      ('O Tanne',                                    0),
                      ('O Tannen',                                   0),
                      ('O Tannenb',                                  0),
                      ('O Tannenba',                                 0),
                      ('O Tannenbau',                                0),
                      ('O Tannenbaum',                               0),
                      ('O Tannenbaum, w',                            0),
                      ('O Tannenbaum, wi',                           0),
                      ('O Tannenbaum, wie',                          0),
                      ('O Tannenbaum, wie t',                        0),
                      ('O Tannenbaum, wie tr',                       0),
                      ('O Tannenbaum, wie tre',                      0),
                      ('O Tannenbaum, wie treu',                     0),
                      ('O Tannenbaum, wie treu s',                   0),
                      ('O Tannenbaum, wie treu si',                  0),
                      ('O Tannenbaum, wie treu sin',                 0),
                      ('O Tannenbaum, wie treu sind',                0),
                      ('O Tannenbaum, wie treu sind d',              0),
                      ('O Tannenbaum, wie treu sind de',             0),
                      ('O Tannenbaum, wie treu sind dei',            0),
                      ('O Tannenbaum, wie treu sind dein',           0),
                      ('O Tannenbaum, wie treu sind deine',          0),
                      ('O Tannenbaum, wie treu sind deine Blätt',    0),
                      ('O Tannenbaum, wie treu sind deine Blätte',   0),
                      ('O Tannenbaum, wie treu sind deine Blätter',  0),
                      ('O Tannenbaum, wie treu sind deine Blätter!', 0);

